#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    for i in range(1,n):
        j = i
        val = arr[i]
        while val<arr[i-1] and i>0:
            arr[i] = arr[i-1]
            i -= 1
            for index in range(n):
                print(arr[index], end=' ')
            print()
        arr[i] = val
        if i!=j:
            for index in range(n):
                print(arr[index], end=' ')

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
